theme: jekyll-theme-cayman
title: ""
description: "A personal academic website."
baseurl: ""
url: "https://foty-hub.github.io"
author:
  name: "Alex Inch"
  email: ""

collections:
  posts:
    output: true
    permalink: /blog/:title
