theme: jekyll-theme-cayman
title: "Alex Inch Portfolio"
description: "A personal academic website showcasing research, publications, and projects."
baseurl: ""
url: "https://foty-hub.github.io"
author:
  name: "Your Name"
  email: "your.email@example.com"