theme: jekyll-theme-cayman
title: ""
description: "A personal academic website."
baseurl: ""
url: "https://foty-hub.github.io"
author:
  name: "Alex Inch"
  email: ""

# Site-wide content max width (CSS length)
max_width: "820px"

collections:
  posts:
    output: true
    permalink: /blog/:title
social:
  linkedin: "https://www.linkedin.com/in/alex-inch/"
  github: "https://github.com/foty-hub"
  x: "https://x.com/alexinch_ai"
  bluesky: "https://bsky.app/profile/alexinch.bsky.social"
